### Criar um post
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjcsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ5MTY1MTU3LCJleHAiOjE3NDkyNTE1NTd9.QCdvEX_7Fz0mD78XlmPyUEvY3m4LV2qYS-M6sy2Wb84

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Meu primeiro post",
  "content": "Conteúdo do post aqui",
  "authorId": 2
}

### Buscar todos os posts
GET http://localhost:3000/posts

### Buscar post por ID
GET http://localhost:3000/posts/2

### Buscar todos os posts de um autor
GET http://localhost:3000/posts/author/2

### Atualizar um post
PATCH http://localhost:3000/posts/3
Content-Type: application/json

{
  "title": "Post atualizado",
  "content": "Novo conteúdo"
}

### Deletar um post
DELETE http://localhost:3000/posts/3
